# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#

#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Finding Mestizaje in the Archive'
description:      'A capstone project submitted in fulfillment of the requirements for the degree of MA in Archives and Public History, NYU. '
url:              'https://katelynautumn28.github.io' #CHANGE THIS
baseurl:          '/findingmestizaje' #CHANGE THIS
copyright:        'Katelyn Landry, 2025'
logo:             '/img/book.png'
default_thumb:    '/img/default.png'
metadata: 'findingmestizaje' #CHANGE THIS; exclude the file extension, i.e. .csv

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/
# YOU MUST CHANGE findingmestizaje, medfrag_item, and raw_images/medfragments TO YOUR OWN COLLECTION FILES TO MAKE THE SITE WORK!

collections:
  exhibits:
    output: true
  findingmestizaje: # name of collection; CHANGE THIS
    output: true # makes sure pages are output as html files
    layout: 'findingmestizaje_item' # the layout for the pages to use; CHANGE THIS
    metadata:
      source: 'findingmestizaje.csv' # path to the metadata file within `_data`; CHANGE THIS
    images:
      source: 'raw_images/findingmestizaje_images' # path to the directory of images within `_data`; CHANGE THIS

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      findingmestizaje:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - agent
          - _dateStart
          - _dateEnd
          - description
          - language
          - location
          - _tags
          - credit
          - citation
          - worktype

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Browse the Collection'
    link: '/collection/'   
  - label: 'Timeline'
    link: '/timeline/'
  - label: 'Map'
    link: '/map.html'
  - label: 'Analysis'
    sub:
      - label: 'Introduction'
        link: '/analysis/intro/'
      - label: 'Methods'
        link: '/analysis/methods/'
      - label: 'Results'
        link: '/analysis/results/'
  - label: 'Data'
    link: '/data/'
  - label: 'Search'
    link: '/search/'
  - label: 'About'
    sub:
      - label: 'About WaxBuilder'
        link: '/about/waxbuilder/'
      - label: 'About the Project'
        link: '/about/project/'
 
  

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/katelynautumn28/findingmestizaje'
    - label: 'Credits'
      link: '/credits'
    - label: 'Wax Wiki'
      link: 'https://minicomp.github.io/wiki/wax/'
  logos:
    - img: '/img/book.png'

# FIN
